services:
  blog:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - blog-data
  blog-data:
    image: 'postgres:14'
    env_file: .env
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: sakyga
      POSTGRES_PASSWORD: 1234
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
volumes:
  pg-data: